services:
  postgres:
    container_name: 'shortly-postgres'
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=shortly
      - POSTGRES_USER=shortly
      - POSTGRES_DB=shortly
    ports:
      - '5442:5432'
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
